In [1]:
import numpy as np
import pandas as pd

In [24]:
df=pd.read_csv("healthcare_data_cleaning_dataset.csv")
df.head()

,Patient_ID,Age,Gender,City,Diagnosis,Hospital_Visits,Treatment_Cost,Insurance_Coverage,Admission_Date
0,17270,35.0,Male,Bangalore,Hypertension,13,41010.0,1,2023-11-30
1,10860,21.0,Female,Hyderabad,Flu,11,12194.0,1,2023-02-23
2,15390,77.0,Female,Bangalore,Asthma,2,45086.0,0,2023-03-14
3,15191,79.0,Female,Mumbai,Asthma,13,40842.0,0,2023-08-01
4,15734,60.0,Female,Delhi,Asthma,1,9873.0,1,2023-06-20

**Q1. Missing Data Identification
Scenario:
The hospital suspects incomplete patient records.
Task:
Identify missing values in each column
Calculate percentage of missing data**

In [7]:
# Missing values in each column
df.isnull().sum()
# Percentage of missing data
(df.isnull().sum()/len(df))*100

Patient_ID             0.000000
Age                   11.764706
Gender                 0.000000
City                   0.000000
Diagnosis              0.000000
Hospital_Visits        0.000000
Treatment_Cost        11.627451
Insurance_Coverage     0.000000
Admission_Date         0.000000
dtype: float64

**Q2. Handling Missing Age
Scenario:Age is critical for medical analysis, but some values are missing.
Task:
Replace missing Age values with an appropriate method
Justify your choice (mean/median)**

In [7]:
df['Age']=df['Age'].fillna(df['Age'].median())
df

,Patient_ID,Age,Gender,City,Diagnosis,Hospital_Visits,Treatment_Cost,Insurance_Coverage,Admission_Date
0,17270,35.0,Male,Bangalore,Hypertension,13,41010.0,1,2023-11-30
1,10860,21.0,Female,Hyderabad,Flu,11,12194.0,1,2023-02-23
2,15390,77.0,Female,Bangalore,Asthma,2,45086.0,0,2023-03-14
3,15191,79.0,Female,Mumbai,Asthma,13,40842.0,0,2023-08-01
4,15734,60.0,Female,Delhi,Asthma,1,9873.0,1,2023-06-20
...,...,...,...,...,...,...,...,...,...
5095,11764,50.0,Female,Mumbai,COVID-19,15,24797.0,0,2023-09-22
5096,17597,50.0,Female,Chennai,Asthma,2,24797.0,0,2023-06-26
5097,19171,50.0,Female,Mumbai,Flu,1,24797.0,1,2023-12-31
5098,13854,50.0,Female,Bangalore,Flu,17,24797.0,0,2023-01-18
5099,14859,50.0,Male,Delhi,Hypertension,19,24797.0,0,2023-08-28

**Missing Age values are handled using the median imputation method. The median is preferred over the mean because it is robust to outliers and provides a more accurate central value for skewed data. This ensures that the dataset remains consistent and suitable for analysis.**

**Q3. Handling Missing Treatment Cost
Scenario:
Treatment cost is highly skewed due to expensive treatments.
Task:
Handle missing Treatment_Cost values
Choose the correct imputation method and explain why**

In [4]:
df['Treatment_Cost']=df['Treatment_Cost'].fillna(df['Treatment_Cost'].median())
df

,Patient_ID,Age,Gender,City,Diagnosis,Hospital_Visits,Treatment_Cost,Insurance_Coverage,Admission_Date
0,17270,35.0,Male,Bangalore,Hypertension,13,41010.0,1,2023-11-30
1,10860,21.0,Female,Hyderabad,Flu,11,12194.0,1,2023-02-23
2,15390,77.0,Female,Bangalore,Asthma,2,45086.0,0,2023-03-14
3,15191,79.0,Female,Mumbai,Asthma,13,40842.0,0,2023-08-01
4,15734,60.0,Female,Delhi,Asthma,1,9873.0,1,2023-06-20
...,...,...,...,...,...,...,...,...,...
5095,11764,NaN,Female,Mumbai,COVID-19,15,24797.0,0,2023-09-22
5096,17597,NaN,Female,Chennai,Asthma,2,24797.0,0,2023-06-26
5097,19171,NaN,Female,Mumbai,Flu,1,24797.0,1,2023-12-31
5098,13854,NaN,Female,Bangalore,Flu,17,24797.0,0,2023-01-18
5099,14859,NaN,Male,Delhi,Hypertension,19,24797.0,0,2023-08-28

**Why Median is Used:**
- Median is used because the dataset is highly skewed.
- Median is the middle value.
- It is not affected by extreme values (outliers).
- It gives a more realistic replacement.
- Maintains the overall distribution of the data.
- Prevents bias caused by extreme values.
- Keeps the dataset balanced and reliable.
- Improves the accuracy of analysis and models.

**Q4. Duplicate Patient Records
Scenario:
Some patient records were entered multiple times.
Task:
Identify duplicate rows
Remove duplicates
Compare dataset size before and after**

In [25]:
before_size=df.shape
print(before_size)
# Duplicate rows
df.duplicated().sum()
# Remove duplicates
df=df.drop_duplicates()
after_size=df.shape
print(after_size)
# Compare
print("Size before removing duplicates:", before_size)
print("Size after removing duplicates:", after_size)

(5100, 9)
(5001, 9)
Size before removing duplicates: (5100, 9)
Size after removing duplicates: (5001, 9)

**Q5. Invalid Age Values (Data Quality Check)
Scenario:
Some patients have unrealistic age values (e.g., >100 or <0).
Task:
Detect such records
Decide whether to remove or correct them**

In [26]:
df[(df['Age'] < 0) | (df['Age'] > 100)]

Empty DataFrame
Columns: [Patient_ID, Age, Gender, City, Diagnosis, Hospital_Visits, Treatment_Cost, Insurance_Coverage, Admission_Date]
Index: []

**No invalid age values were found, so no cleaning was required.**

**Q6. Outlier Detection (Treatment Cost)
Scenario:
Extreme treatment costs are affecting analysis.
Task:
Detect outliers using IQR method
Display number of outliers**

In [29]:
Q1 = df['Treatment_Cost'].quantile(0.25)
Q3 = df['Treatment_Cost'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
outliers = df[(df['Treatment_Cost'] < lower) | (df['Treatment_Cost'] > upper)]
print(outliers)

      Patient_ID   Age  Gender       City     Diagnosis  Hospital_Visits  \
53         13152  91.0  Female    Chennai      COVID-19               13
86         10064  28.0  Female  Hyderabad  Hypertension               16
124        17035  59.0    Male      Delhi           Flu                9
183        15855  36.0    Male     Mumbai      Diabetes                1
215        19561  29.0    Male     Mumbai           Flu               16
332        11686  51.0    Male      Delhi        Asthma               16
382        10876  58.0  Female  Bangalore  Hypertension                1
416        14070   NaN    Male  Hyderabad           Flu                6
452        10851  42.0  Female  Bangalore      COVID-19               15
796        18150  37.0  Female  Bangalore           Flu               17
833        19361  41.0  Female      Delhi      Diabetes               19
1127       10943  26.0  Female      Delhi        Asthma               19
1176       18232  29.0    Male    Chennai      Diabetes               10
1219       15408  44.0    Male      Delhi  Hypertension               10
1392       14876  70.0    Male     Mumbai      Diabetes               11
1613       16090  15.0  Female  Hyderabad      COVID-19                2
1729       10575  79.0    Male    Chennai      Diabetes                9
1771       15342  79.0  Female  Bangalore      Diabetes               12
2077       11048  77.0    Male    Chennai        Asthma                8
2166       10593  44.0  Female      Delhi      COVID-19               18
2210       12711  36.0  Female     Mumbai      Diabetes               15
2228       18551  86.0    Male  Bangalore  Hypertension               17
2382       10830  35.0    Male      Delhi      Diabetes               18
2449       10204   0.0    Male      Delhi      COVID-19               12
2531       12113  99.0    Male     Mumbai           Flu                8
2561       13525   NaN    Male  Bangalore      COVID-19               19
2694       14088  56.0  Female  Bangalore  Hypertension                8
2847       17922   NaN  Female      Delhi      COVID-19               12
3213       19120  95.0  Female    Chennai           Flu                2
3279       10674  10.0  Female     Mumbai  Hypertension               17
3361       14781  21.0  Female    Chennai      Diabetes                3
3659       13197  61.0  Female    Chennai      COVID-19               10
3830       18933  15.0  Female     Mumbai           Flu                9
3855       10644  77.0    Male      Delhi  Hypertension               11
3874       19763  86.0  Female      Delhi      Diabetes               16
4060       15944  72.0  Female     Mumbai        Asthma               16
4072       10857  80.0    Male     Mumbai      COVID-19               14
4207       12690  76.0    Male  Hyderabad        Asthma               14
4292       12430  25.0    Male    Chennai      Diabetes               11
4414       18102  91.0    Male  Hyderabad  Hypertension                2
4549       17545  12.0  Female      Delhi      Diabetes               13
4582       16646   NaN    Male      Delhi           Flu                4
4617       10896  88.0  Female    Chennai      COVID-19                3
4625       11449   NaN  Female  Hyderabad      Diabetes                5
4629       14117  82.0    Male  Hyderabad  Hypertension               17
4656       17384  65.0  Female    Chennai        Asthma               10
4740       11764   NaN  Female     Mumbai      COVID-19               15
4780       10717  52.0  Female     Mumbai      Diabetes               17
4831       11827   NaN    Male    Chennai           Flu                1
4895       11170   1.0  Female  Bangalore           Flu                3

      Treatment_Cost  Insurance_Coverage Admission_Date
53     199702.965333                   0     2023-01-24
86     199702.965333                   0     2023-02-18
124    199702.965333                   0     2023-04-27
183    199702.965333                   0     2023-01-16
215    199702.965333                   0     2023-05-31
332    199702.965333                   1     2023-03-31
382    199702.965333                   1     2023-10-21
416    199702.965333                   0     2023-08-18
452    199702.965333                   0     2023-06-27
796    199702.965333                   0     2023-03-26
833    199702.965333                   0     2023-10-08
1127   199702.965333                   0     2023-06-02
1176   199702.965333                   1     2023-07-10
1219   199702.965333                   0     2023-04-14
1392   199702.965333                   1     2023-12-27
1613   199702.965333                   0     2023-10-07
1729   199702.965333                   0     2023-11-28
1771   199702.965333                   1     2023-08-31
2077   199702.965333                   1     2023-09-30
2166   199702.965333                   1     2023-02-13
2210   199702.965333                   0     2023-03-19
2228   199702.965333                   0     2023-11-06
2382   199702.965333                   1     2023-04-17
2449   199702.965333                   0     2023-09-20
2531   199702.965333                   1     2023-04-23
2561   199702.965333                   0     2023-01-16
2694   199702.965333                   0     2023-10-06
2847   199702.965333                   0     2023-08-01
3213   199702.965333                   0     2023-05-12
3279   199702.965333                   1     2023-12-09
3361   199702.965333                   1     2023-10-09
3659   199702.965333                   1     2023-11-06
3830   199702.965333                   1     2023-09-09
3855   199702.965333                   0     2023-09-15
3874   199702.965333                   0     2023-03-30
4060   199702.965333                   0     2023-02-22
4072   199702.965333                   0     2023-11-05
4207   199702.965333                   1     2023-05-16
4292   199702.965333                   0     2023-01-01
4414   199702.965333                   1     2023-08-01
4549   199702.965333                   0     2023-11-11
4582   199702.965333                   1     2023-02-27
4617   199702.965333                   1     2023-01-01
4625   199702.965333                   1     2023-03-28
4629   199702.965333                   1     2023-11-13
4656   199702.965333                   0     2023-05-13
4740   199702.965333                   0     2023-09-22
4780   199702.965333                   0     2023-02-10
4831   199702.965333                   1     2023-07-02
4895   199702.965333                   1     2023-12-06

**Q7. Outlier Treatment
Scenario:
The business team wants to retain all records.
Task:
Apply capping (Winsorization) on Treatment_Cost
Use 5th and 95th percentile**

In [32]:
lower_cap = df['Treatment_Cost'].quantile(0.05)
upper_cap = df['Treatment_Cost'].quantile(0.95)
df['Treatment_Cost'] = df['Treatment_Cost'].clip(lower_cap, upper_cap)
df['Treatment_Cost']

0       41010.000
1       12194.000
2       45086.000
3       40842.000
4        9873.000
          ...
4996          NaN
4997     2915.314
4998    31337.000
4999    39801.000
5095          NaN
Name: Treatment_Cost, Length: 5001, dtype: float64

**Q8. Transformation
Scenario:
Treatment cost is highly skewed.
Task:
Apply log transformation
Create a new column
Compare before vs after distribution**

In [34]:
df['Log_Treatment_Cost'] = np.log(df['Treatment_Cost'])
df['Log_Treatment_Cost']

0       10.621571
1        9.408699
2       10.716327
3       10.617466
4        9.197559
          ...
4996          NaN
4997     7.977733
4998    10.352555
4999    10.591647
5095          NaN
Name: Log_Treatment_Cost, Length: 5001, dtype: float64

**Q9. Time-Based Missing Handling
Scenario:
Admission dates should follow a logical sequence.
Task:
Sort data by Admission_Date
Apply forward fill or backward fill where appropriate
Justify your choice**

In [41]:
df['Admission_Date'] = pd.to_datetime(df['Admission_Date'])
df = df.sort_values(by='Admission_Date')
df = df.fillna(method='ffill')
df

/var/folders/vz/2g7fn3gs6wq2dyzm76_bpc4m0000gn/T/ipykernel_1202/839506179.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill')

,Patient_ID,Age,Gender,City,Diagnosis,Hospital_Visits,Treatment_Cost,Insurance_Coverage,Admission_Date,Log_Treatment_Cost
2932,19591,91.0,Male,Chennai,Asthma,3,32149.000,0,2023-01-01,10.378137
2702,17230,41.0,Male,Bangalore,Hypertension,18,12398.000,0,2023-01-01,9.425290
1551,10959,17.0,Male,Chennai,Hypertension,8,12568.000,1,2023-01-01,9.438909
4329,17692,64.0,Male,Chennai,Hypertension,19,36377.000,1,2023-01-01,10.501692
866,15966,49.0,Female,Mumbai,Hypertension,10,43720.000,1,2023-01-01,10.685561
...,...,...,...,...,...,...,...,...,...,...
2593,11125,32.0,Female,Mumbai,Flu,16,42518.000,0,2023-12-31,10.657683
3013,13630,73.0,Male,Bangalore,Diabetes,3,2915.314,0,2023-12-31,7.977733
4744,12671,20.0,Female,Mumbai,COVID-19,8,22863.000,1,2023-12-31,10.037275
3456,19171,20.0,Female,Mumbai,Flu,1,22863.000,1,2023-12-31,10.037275
3133,11238,24.0,Male,Hyderabad,Asthma,2,9847.000,0,2023-12-31,9.194922

Forward Fill is Used
ju
- Works well for time-series data
- Maintains data continuity
- Simple and effective when values do not change drastically in a short time